name: Send Discord Message

on:
  push:

jobs:
  send-discord-message:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Message
        run: |
          curl -X POST -F 'content=${{ github.actor}}が${{ github.event.repository.name }}にpushした！ありがとう！
          コミットメッセージ：${{ github.event.head_commit.message }}
          コミットURL：https://github.com/${{ github.repository }}/commit/${{ github.sha }}' "${{ secrets.DISCORD_WEBHOOK_URL }}"